name: Deploy React App to gh-pages

on:
  push:
    paths:
      - "package.json"
      - ".github/**"
      - "public/**"
      - "src/**"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Deploy
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git --work-tree build add --all
        git commit -m "Automated deployment to GitHub Pages"
        git push origin HEAD:gh-pages --force
