name: React Tests
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
              node-version: '20'
        - name: Install Dependencies
          uses: Borales/actions-yarn@v5.0.0
          with:
              cmd: install
        - name: Run Tests
          uses: Borales/actions-yarn@v5.0.0
          with:
              cmd: test
